### ISSUE TITLE
Failing feature extraction: num_nonling_tstars_between

### ISSUE THREAD

**Issue by jrmyp** [irit-melodi/educe#75]
I ran `irit-stac gather` on the latest annotations, with the new feature set. The following appeared:

```
File "/home/perret/Slave/educe/educe/stac/learning/features.py", line 636, in num_nonling_tstars_between
    min(turn_id(x) for x in _edu2.dialogue_turns) - 1)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Command '['stac-learning', 'extract', 'data/combined', 'lexicon', 'TMP/2015-09-28T1242', '--anno', '(?i)bronze|silver|gold']' returned non-zero exit status 1
```

I'm investigating this and will update with more info. I suppose there are some non-fake root EDUs that also have `None` as turn_id.

**Comment by moreymat** [comment]
Thanks for reporting this.

I am able to reproduce this bug which is due to annotations that somehow got lost in the process.
This got under `stac-check`'s radar, so I must remedy this and fix the lost information.

Hence, I think it is better if I take over the investigations on this.

**Comment by moreymat** [comment]
The bug is in the corpus (turn information lost), not in the code.

I was willing to add a test for this in `stac-check`, but a unique occurrence does not justify this.

**Comment by moreymat** [comment]
@jrmyp I fixed the bug in `frozen` and the current version as well. You should be able to re-run the pipeline.
